import { hmwUnit } from './define.ts';

const traits = [
  'Armor',
  'Bounty',
  'Bounty Hunter',
  'Capital Ship',
  'Clone',
  'Condition',
  'Creature',
  'Disaster',
  'Droid',
  'Endor',
  'Ewok',
  'Fighter',
  'First Order',
  'Force',
  'Fortification',
  'Fringe',
  'Gambit',
  'Gungan',
  'Hutt',
  'Imperial',
  'Innate',
  'Inquisitor',
  'Item',
  'Jawa',
  'Jedi',
  'Kaminoan',
  'Kashyyyk',
  'Law',
  'Learned',
  'Lightsaber',
  'Mandalorian',
  'Modification',
  'Musician',
  'Naboo',
  'New Republic',
  'Night',
  'Nihil',
  'Official',
  'Pilot',
  'Plan',
  'Rebel',
  'Republic',
  'Resistance',
  'Separatist',
  'Sith',
  'Spectre',
  'Speeder',
  'Supply',
  'Tactic',
  'Tank',
  'Tatooine',
  'Transport',
  'Trick',
  'Trooper',
  'Tusken',
  "Twi'lek",
  'Undead',
  'Underworld',
  'Vehicle',
  'Walker',
  'Weapon',
  'Wookiee',
] as const;

export const hmwTheFirstLegionVadersFist = hmwUnit('the-first-legion--vader-s-fist', {
  triggers: [
    {
      id: 'attack',
      timing: 'attack',
      effects: [
        {
          kind: 'choose-mode',
          options: traits.map(trait => ({
            id: trait.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
            effects: [{ kind: 'lose-enemy-trait', trait }],
          })),
        },
      ],
    },
  ],
});
