export function generateDisplayName() {
  const adverbs = [
    'Very',
    'Quite',
    'Not very',
    'Extremely',
    'Somewhat',
    'Truly',
    'Almost',
    'Barely',
    'Immensely',
    'Moderately',
    'Slightly',
    'Unusually',
    'Ridiculously',
    'Hilariously',
    'Exceptionally',
    'Relatively',
    'Remarkably',
    'Incredibly',
    'Oddly',
    'Surprisingly',
    'Insanely',
    'Perfectly',
    'Totally',
    'Deeply',
    'Entirely',
    'Partially',
    'Mostly',
    'Vastly',
    'Rarely',
    'Unbelievably',
  ];
  const adjectives = [
    'honorable',
    'fortunate',
    'unhelpful',
    'courageous',
    'mischievous',
    'brave',
    'wise',
    'grumpy',
    'clumsy',
    'famous',
    'infamous',
    'awkward',
    'calm',
    'energetic',
    'fearless',
    'brilliant',
    'witty',
    'lazy',
    'reliable',
    'reckless',
    'curious',
    'helpful',
    'grateful',
    'unlucky',
    'mighty',
    'gentle',
    'clever',
    'loyal',
    'chaotic',
    'mysterious',
  ];
  const entities = [
    'Yoda',
    'Darth Vader',
    'Grogu',
    'Leia',
    'Luke Skywalker',
    'Chewbacca',
    'Han Solo',
    'R2-D2',
    'C-3PO',
    'Obi-Wan Kenobi',
    'Palpatine',
    'Boba Fett',
    'Jabba the Hutt',
    'Mace Windu',
    'Anakin Skywalker',
    'Padmé Amidala',
    'Lando Calrissian',
    'Ahsoka Tano',
    'Kylo Ren',
    'Rey',
    'Finn',
    'Poe Dameron',
    'BB-8',
    'The Mandalorian',
    'Count Dooku',
    'Qui-Gon Jinn',
    'General Grievous',
    'Wicket',
    'Admiral Ackbar',
    'Snoke',
    'Maz Kanata',
  ];
  const titles = [
    'apprentice',
    'neighbor',
    'mom',
    'best friend',
    'nemesis',
    'mentor',
    'student',
    'rival',
    'admirer',
    'ally',
    'enemy',
    'assistant',
    'commander',
    'pilot',
    'warrior',
    'strategist',
    'guardian',
    'smuggler',
    'bounty hunter',
    'sibling',
    'clone',
    'co-pilot',
    'mechanic',
    'leader',
    'explorer',
    'mercenary',
    'traitor',
    'hero',
    'villain',
    'sidekick',
  ];

  // Randomly select one from each array
  const adverb = adverbs[Math.floor(Math.random() * adverbs.length)];
  const adjective = adjectives[Math.floor(Math.random() * adjectives.length)];
  const entity = entities[Math.floor(Math.random() * entities.length)];
  const title = titles[Math.floor(Math.random() * titles.length)];

  // Combine them into a display name
  return `${adverb} ${adjective} ${entity}'s ${title}`;
}
