export default [
  {
    currency_code: 'AFN',
    name: 'Afghan Afghani',
    symbol: '؋',
    ranking: 17,
  },
  {
    currency_code: 'ALL',
    name: 'Albanian Lek',
    symbol: 'L',
    ranking: 17,
  },
  {
    currency_code: 'DZD',
    name: 'Algerian Dinar',
    symbol: 'د.ج',
    ranking: 17,
  },
  {
    currency_code: 'AOA',
    name: 'Angolan Kwanza',
    symbol: 'Kz',
    ranking: 17,
  },
  {
    currency_code: 'ARS',
    name: 'Argentine Peso',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'AMD',
    name: 'Armenian Dram',
    symbol: '֏',
    ranking: 17,
  },
  {
    currency_code: 'AWG',
    name: 'Aruban Florin',
    symbol: 'ƒ',
    ranking: 17,
  },
  {
    currency_code: 'AUD',
    name: 'Australian Dollar',
    symbol: '$',
    ranking: 7,
  },
  {
    currency_code: 'AZN',
    name: 'Azerbaijani Manat',
    symbol: '₼',
    ranking: 17,
  },
  {
    currency_code: 'BSD',
    name: 'Bahamian Dollar',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'BHD',
    name: 'Bahraini Dinar',
    symbol: '.د.ب',
    ranking: 17,
  },
  {
    currency_code: 'BDT',
    name: 'Bangladeshi Taka',
    symbol: '৳',
    ranking: 17,
  },
  {
    currency_code: 'BBD',
    name: 'Barbadian Dollar',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'BYN',
    name: 'Belarusian Ruble',
    symbol: 'Br',
    ranking: 17,
  },
  {
    currency_code: 'BZD',
    name: 'Belize Dollar',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'BMD',
    name: 'Bermudian Dollar',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'BTN',
    name: 'Bhutanese Ngultrum',
    symbol: 'Nu.',
    ranking: 17,
  },
  {
    currency_code: 'BOB',
    name: 'Bolivian Boliviano',
    symbol: 'Bs.',
    ranking: 17,
  },
  {
    currency_code: 'BAM',
    name: 'Bosnia-Herzegovina Convertible Mark',
    symbol: 'KM',
    ranking: 17,
  },
  {
    currency_code: 'BWP',
    name: 'Botswanan Pula',
    symbol: 'P',
    ranking: 17,
  },
  {
    currency_code: 'BRL',
    name: 'Brazilian Real',
    symbol: 'R$',
    ranking: 15,
  },
  {
    currency_code: 'GBP',
    name: 'British Pound Sterling',
    symbol: '£',
    ranking: 4,
  },
  {
    currency_code: 'BND',
    name: 'Brunei Dollar',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'BGN',
    name: 'Bulgarian Lev',
    symbol: 'лв',
    ranking: 17,
  },
  {
    currency_code: 'BIF',
    name: 'Burundian Franc',
    symbol: 'Fr',
    ranking: 17,
  },
  {
    currency_code: 'KHR',
    name: 'Cambodian Riel',
    symbol: '៛',
    ranking: 17,
  },
  {
    currency_code: 'CAD',
    name: 'Canadian Dollar',
    symbol: '$',
    ranking: 6,
  },
  {
    currency_code: 'CVE',
    name: 'Cape Verdean Escudo',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'KYD',
    name: 'Cayman Islands Dollar',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'XOF',
    name: 'CFA Franc BCEAO',
    symbol: 'Fr',
    ranking: 17,
  },
  {
    currency_code: 'XAF',
    name: 'CFA Franc BEAC',
    symbol: 'Fr',
    ranking: 17,
  },
  {
    currency_code: 'XPF',
    name: 'CFP Franc',
    symbol: 'Fr',
    ranking: 17,
  },
  {
    currency_code: 'CLP',
    name: 'Chilean Peso',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'CNY',
    name: 'Chinese Yuan',
    symbol: '¥',
    ranking: 8,
  },
  {
    currency_code: 'COP',
    name: 'Colombian Peso',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'KMF',
    name: 'Comorian Franc',
    symbol: 'Fr',
    ranking: 17,
  },
  {
    currency_code: 'CDF',
    name: 'Congolese Franc',
    symbol: 'Fr',
    ranking: 17,
  },
  {
    currency_code: 'CRC',
    name: 'Costa Rican Colón',
    symbol: '₡',
    ranking: 17,
  },
  {
    currency_code: 'HRK',
    name: 'Croatian Kuna',
    symbol: 'kn',
    ranking: 17,
  },
  {
    currency_code: 'CUP',
    name: 'Cuban Peso',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'CZK',
    name: 'Czech Republic Koruna',
    symbol: 'Kč',
    ranking: 17,
  },
  {
    currency_code: 'DKK',
    name: 'Danish Krone',
    symbol: 'kr',
    ranking: 17,
  },
  {
    currency_code: 'DJF',
    name: 'Djiboutian Franc',
    symbol: 'Fr',
    ranking: 17,
  },
  {
    currency_code: 'DOP',
    name: 'Dominican Peso',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'XCD',
    name: 'East Caribbean Dollar',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'EGP',
    name: 'Egyptian Pound',
    symbol: '£',
    ranking: 17,
  },
  {
    currency_code: 'ERN',
    name: 'Eritrean Nakfa',
    symbol: 'Nfk',
    ranking: 17,
  },
  {
    currency_code: 'ETB',
    name: 'Ethiopian Birr',
    symbol: 'Br',
    ranking: 17,
  },
  {
    currency_code: 'EUR',
    name: 'Euro',
    symbol: '€',
    ranking: 2,
  },
  {
    currency_code: 'FKP',
    name: 'Falkland Islands Pound',
    symbol: '£',
    ranking: 17,
  },
  {
    currency_code: 'FOK',
    name: 'Faroese Krona',
    symbol: '',
    ranking: 17,
  },
  {
    currency_code: 'FJD',
    name: 'Fijian Dollar',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'GMD',
    name: 'Gambian Dalasi',
    symbol: 'D',
    ranking: 17,
  },
  {
    currency_code: 'GEL',
    name: 'Georgian Lari',
    symbol: '₾',
    ranking: 17,
  },
  {
    currency_code: 'GHS',
    name: 'Ghanaian Cedi',
    symbol: '₵',
    ranking: 17,
  },
  {
    currency_code: 'GIP',
    name: 'Gibraltar Pound',
    symbol: '£',
    ranking: 17,
  },
  {
    currency_code: 'GTQ',
    name: 'Guatemalan Quetzal',
    symbol: 'Q',
    ranking: 17,
  },
  {
    currency_code: 'GGP',
    name: 'Guernsey Pound',
    symbol: '£',
    ranking: 17,
  },
  {
    currency_code: 'GNF',
    name: 'Guinean Franc',
    symbol: 'Fr',
    ranking: 17,
  },
  {
    currency_code: 'GYD',
    name: 'Guyanaese Dollar',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'HTG',
    name: 'Haitian Gourde',
    symbol: 'G',
    ranking: 17,
  },
  {
    currency_code: 'HNL',
    name: 'Honduran Lempira',
    symbol: 'L',
    ranking: 17,
  },
  {
    currency_code: 'HKD',
    name: 'Hong Kong Dollar',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'HUF',
    name: 'Hungarian Forint',
    symbol: 'Ft',
    ranking: 17,
  },
  {
    currency_code: 'ISK',
    name: 'Icelandic Króna',
    symbol: 'kr',
    ranking: 17,
  },
  {
    currency_code: 'INR',
    name: 'Indian Rupee',
    symbol: '₹',
    ranking: 14,
  },
  {
    currency_code: 'IDR',
    name: 'Indonesian Rupiah',
    symbol: 'Rp',
    ranking: 17,
  },
  {
    currency_code: 'IRR',
    name: 'Iranian Rial',
    symbol: '﷼',
    ranking: 17,
  },
  {
    currency_code: 'IQD',
    name: 'Iraqi Dinar',
    symbol: 'ع.د',
    ranking: 17,
  },
  {
    currency_code: 'ILS',
    name: 'Israeli New Sheqel',
    symbol: '₪',
    ranking: 17,
  },
  {
    currency_code: 'JMD',
    name: 'Jamaican Dollar',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'JPY',
    name: 'Japanese Yen',
    symbol: '¥',
    ranking: 3,
  },
  {
    currency_code: 'JEP',
    name: 'Jersey Pound',
    symbol: '£',
    ranking: 17,
  },
  {
    currency_code: 'JOD',
    name: 'Jordanian Dinar',
    symbol: 'د.ا',
    ranking: 17,
  },
  {
    currency_code: 'KZT',
    name: 'Kazakhstani Tenge',
    symbol: '₸',
    ranking: 17,
  },
  {
    currency_code: 'KES',
    name: 'Kenyan Shilling',
    symbol: 'Sh',
    ranking: 17,
  },
  {
    currency_code: 'KID',
    name: 'Kiribati Dollar',
    symbol: '',
    ranking: 17,
  },
  {
    currency_code: 'KWD',
    name: 'Kuwaiti Dinar',
    symbol: 'د.ك',
    ranking: 17,
  },
  {
    currency_code: 'KGS',
    name: 'Kyrgystani Som',
    symbol: 'с',
    ranking: 17,
  },
  {
    currency_code: 'LAK',
    name: 'Laotian Kip',
    symbol: '₭',
    ranking: 17,
  },
  {
    currency_code: 'LBP',
    name: 'Lebanese Pound',
    symbol: 'ل.ل',
    ranking: 17,
  },
  {
    currency_code: 'LSL',
    name: 'Lesotho Loti',
    symbol: 'L',
    ranking: 17,
  },
  {
    currency_code: 'LRD',
    name: 'Liberian Dollar',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'LYD',
    name: 'Libyan Dinar',
    symbol: 'ل.د',
    ranking: 17,
  },
  {
    currency_code: 'MOP',
    name: 'Macanese Pataca',
    symbol: 'P',
    ranking: 17,
  },
  {
    currency_code: 'MKD',
    name: 'Macedonian Denar',
    symbol: 'ден',
    ranking: 17,
  },
  {
    currency_code: 'MGA',
    name: 'Malagasy Ariary',
    symbol: 'Ar',
    ranking: 17,
  },
  {
    currency_code: 'MWK',
    name: 'Malawian Kwacha',
    symbol: 'MK',
    ranking: 17,
  },
  {
    currency_code: 'MYR',
    name: 'Malaysian Ringgit',
    symbol: 'RM',
    ranking: 17,
  },
  {
    currency_code: 'MVR',
    name: 'Maldivian Rufiyaa',
    symbol: 'ރ.',
    ranking: 17,
  },
  {
    currency_code: 'IMP',
    name: 'Manx pound',
    symbol: '£',
    ranking: 17,
  },
  {
    currency_code: 'MRU',
    name: 'Mauritanian Ouguiya',
    symbol: '',
    ranking: 17,
  },
  {
    currency_code: 'MUR',
    name: 'Mauritian Rupee',
    symbol: '₨',
    ranking: 17,
  },
  {
    currency_code: 'MXN',
    name: 'Mexican Peso',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'MDL',
    name: 'Moldovan Leu',
    symbol: 'L',
    ranking: 17,
  },
  {
    currency_code: 'MNT',
    name: 'Mongolian Tugrik',
    symbol: '₮',
    ranking: 17,
  },
  {
    currency_code: 'MAD',
    name: 'Moroccan Dirham',
    symbol: 'د.م.',
    ranking: 17,
  },
  {
    currency_code: 'MZN',
    name: 'Mozambican Metical',
    symbol: 'MT',
    ranking: 17,
  },
  {
    currency_code: 'MMK',
    name: 'Myanmar Kyat',
    symbol: 'Ks',
    ranking: 17,
  },
  {
    currency_code: 'NAD',
    name: 'Namibian Dollar',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'NPR',
    name: 'Nepalese Rupee',
    symbol: '₨',
    ranking: 17,
  },
  {
    currency_code: 'ANG',
    name: 'Netherlands Antillean Guilder',
    symbol: 'ƒ',
    ranking: 17,
  },
  {
    currency_code: 'TWD',
    name: 'New Taiwan Dollar',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'NZD',
    name: 'New Zealand Dollar',
    symbol: '$',
    ranking: 13,
  },
  {
    currency_code: 'NIO',
    name: 'Nicaraguan Córdoba',
    symbol: 'C$',
    ranking: 17,
  },
  {
    currency_code: 'NGN',
    name: 'Nigerian Naira',
    symbol: '₦',
    ranking: 17,
  },
  {
    currency_code: 'NOK',
    name: 'Norwegian Krone',
    symbol: 'kr',
    ranking: 12,
  },
  {
    currency_code: 'OMR',
    name: 'Omani Rial',
    symbol: 'ر.ع.',
    ranking: 17,
  },
  {
    currency_code: 'PKR',
    name: 'Pakistani Rupee',
    symbol: '₨',
    ranking: 17,
  },
  {
    currency_code: 'PAB',
    name: 'Panamanian Balboa',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'PGK',
    name: 'Papua New Guinean Kina',
    symbol: 'K',
    ranking: 17,
  },
  {
    currency_code: 'PYG',
    name: 'Paraguayan Guarani',
    symbol: '₲',
    ranking: 17,
  },
  {
    currency_code: 'PEN',
    name: 'Peruvian Nuevo Sol',
    symbol: 'S\/',
    ranking: 17,
  },
  {
    currency_code: 'PHP',
    name: 'Philippine Peso',
    symbol: '₱',
    ranking: 17,
  },
  {
    currency_code: 'PLN',
    name: 'Polish Zloty',
    symbol: 'zł',
    ranking: 17,
  },
  {
    currency_code: 'QAR',
    name: 'Qatari Rial',
    symbol: 'ر.ق',
    ranking: 17,
  },
  {
    currency_code: 'RON',
    name: 'Romanian Leu',
    symbol: 'lei',
    ranking: 17,
  },
  {
    currency_code: 'RUB',
    name: 'Russian Ruble',
    symbol: '₽',
    ranking: 16,
  },
  {
    currency_code: 'RWF',
    name: 'Rwandan Franc',
    symbol: 'Fr',
    ranking: 17,
  },
  {
    currency_code: 'SHP',
    name: 'Saint Helena Pound',
    symbol: '£',
    ranking: 17,
  },
  {
    currency_code: 'WST',
    name: 'Samoan Tala',
    symbol: 'T',
    ranking: 17,
  },
  {
    currency_code: 'STN',
    name: 'São Tomé and Príncipe Dobra',
    symbol: 'Db',
    ranking: 17,
  },
  {
    currency_code: 'SAR',
    name: 'Saudi Riyal',
    symbol: 'ر.س',
    ranking: 17,
  },
  {
    currency_code: 'RSD',
    name: 'Serbian Dinar',
    symbol: 'дин',
    ranking: 17,
  },
  {
    currency_code: 'SCR',
    name: 'Seychellois Rupee',
    symbol: '₨',
    ranking: 17,
  },
  {
    currency_code: 'SLE',
    name: 'Sierra Leonean Leone (1964—2022)',
    symbol: '',
    ranking: 17,
  },
  {
    currency_code: 'SGD',
    name: 'Singapore Dollar',
    symbol: '$',
    ranking: 10,
  },
  {
    currency_code: 'SBD',
    name: 'Solomon Islands Dollar',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'SOS',
    name: 'Somali Shilling',
    symbol: 'Sh',
    ranking: 17,
  },
  {
    currency_code: 'ZAR',
    name: 'South African Rand',
    symbol: 'R',
    ranking: 17,
  },
  {
    currency_code: 'KRW',
    name: 'South Korean Won',
    symbol: '₩',
    ranking: 9,
  },
  {
    currency_code: 'SSP',
    name: 'South Sudanese Pound',
    symbol: '£',
    ranking: 17,
  },
  {
    currency_code: 'XDR',
    name: 'Special Drawing Rights',
    symbol: '',
    ranking: 17,
  },
  {
    currency_code: 'LKR',
    name: 'Sri Lankan Rupee',
    symbol: 'Rs',
    ranking: 17,
  },
  {
    currency_code: 'SDG',
    name: 'Sudanese Pound',
    symbol: 'ج.س.',
    ranking: 17,
  },
  {
    currency_code: 'SRD',
    name: 'Surinamese Dollar',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'SZL',
    name: 'Swazi Lilangeni',
    symbol: 'L',
    ranking: 17,
  },
  {
    currency_code: 'SEK',
    name: 'Swedish Krona',
    symbol: 'kr',
    ranking: 11,
  },
  {
    currency_code: 'CHF',
    name: 'Swiss Franc',
    symbol: 'CHF',
    ranking: 5,
  },
  {
    currency_code: 'SYP',
    name: 'Syrian Pound',
    symbol: '£',
    ranking: 17,
  },
  {
    currency_code: 'TJS',
    name: 'Tajikistani Somoni',
    symbol: 'ЅМ',
    ranking: 17,
  },
  {
    currency_code: 'TZS',
    name: 'Tanzanian Shilling',
    symbol: 'Sh',
    ranking: 17,
  },
  {
    currency_code: 'THB',
    name: 'Thai Baht',
    symbol: '฿',
    ranking: 17,
  },
  {
    currency_code: 'TOP',
    name: 'Tongan Paʻanga',
    symbol: 'T$',
    ranking: 17,
  },
  {
    currency_code: 'TTD',
    name: 'Trinidad and Tobago Dollar',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'TND',
    name: 'Tunisian Dinar',
    symbol: 'د.ت',
    ranking: 17,
  },
  {
    currency_code: 'TRY',
    name: 'Turkish Lira',
    symbol: '₺',
    ranking: 17,
  },
  {
    currency_code: 'TMT',
    name: 'Turkmenistani Manat',
    symbol: 'm',
    ranking: 17,
  },
  {
    currency_code: 'TVD',
    name: 'Tuvaluan Dollar',
    symbol: '',
    ranking: 17,
  },
  {
    currency_code: 'UGX',
    name: 'Ugandan Shilling',
    symbol: 'Sh',
    ranking: 17,
  },
  {
    currency_code: 'UAH',
    name: 'Ukrainian Hryvnia',
    symbol: '₴',
    ranking: 17,
  },
  {
    currency_code: 'USD',
    name: 'United States Dollar',
    symbol: '$',
    ranking: 1,
  },
  {
    currency_code: 'UYU',
    name: 'Uruguayan Peso',
    symbol: '$',
    ranking: 17,
  },
  {
    currency_code: 'UZS',
    name: 'Uzbekistan Som',
    symbol: 'лв',
    ranking: 17,
  },
  {
    currency_code: 'VUV',
    name: 'Vanuatu Vatu',
    symbol: 'Vt',
    ranking: 17,
  },
  {
    currency_code: 'VES',
    name: 'Venezuelan Bolívar Soberano',
    symbol: 'Bs.S',
    ranking: 17,
  },
  {
    currency_code: 'VND',
    name: 'Vietnamese Dong',
    symbol: '₫',
    ranking: 17,
  },
  {
    currency_code: 'YER',
    name: 'Yemeni Rial',
    symbol: '﷼',
    ranking: 17,
  },
  {
    currency_code: 'ZMW',
    name: 'Zambian Kwacha',
    symbol: 'ZK',
    ranking: 17,
  },
  {
    currency_code: 'ZWL',
    name: 'Zimbabwean Dollar',
    symbol: '$',
    ranking: 17,
  },
] as const;
