/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Statistics2RouteImport } from './routes/statistics2'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as StatisticsIndexRouteImport } from './routes/statistics/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as MetaIndexRouteImport } from './routes/meta/index'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as LimitedIndexRouteImport } from './routes/limited/index'
import { Route as ComparerIndexRouteImport } from './routes/comparer/index'
import { Route as WantlistsYourRouteImport } from './routes/wantlists/your'
import { Route as WantlistsPublicRouteImport } from './routes/wantlists/public'
import { Route as StatisticsStatisticsLayoutRouteImport } from './routes/statistics/_statisticsLayout'
import { Route as ListsYourRouteImport } from './routes/lists/your'
import { Route as DecksYourRouteImport } from './routes/decks/your'
import { Route as DecksTournamentRouteImport } from './routes/decks/tournament'
import { Route as DecksPublicRouteImport } from './routes/decks/public'
import { Route as DecksFavoriteRouteImport } from './routes/decks/favorite'
import { Route as CollectionsYourRouteImport } from './routes/collections/your'
import { Route as CollectionsPublicRouteImport } from './routes/collections/public'
import { Route as CardsSearchRouteImport } from './routes/cards/search'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as WantlistsWantlistIdIndexRouteImport } from './routes/wantlists/$wantlistId/index'
import { Route as UsersUserIdIndexRouteImport } from './routes/users/$userId/index'
import { Route as TournamentsPlanetaryQualifiersIndexRouteImport } from './routes/tournaments/planetary-qualifiers/index'
import { Route as TournamentsFeaturedIndexRouteImport } from './routes/tournaments/featured/index'
import { Route as TournamentsAllIndexRouteImport } from './routes/tournaments/all/index'
import { Route as TournamentsTournamentIdIndexRouteImport } from './routes/tournaments/$tournamentId/index'
import { Route as ToolsDeckFormatConverterIndexRouteImport } from './routes/tools/deck-format-converter/index'
import { Route as TeamsTeamIdIndexRouteImport } from './routes/teams/$teamId/index'
import { Route as ListsCardListIdIndexRouteImport } from './routes/lists/$cardListId/index'
import { Route as LimitedPublicIndexRouteImport } from './routes/limited/public/index'
import { Route as DecksDeckIdIndexRouteImport } from './routes/decks/$deckId/index'
import { Route as CollectionsCollectionIdIndexRouteImport } from './routes/collections/$collectionId/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as TournamentsTournamentIdMetaRouteImport } from './routes/tournaments/$tournamentId/meta'
import { Route as TournamentsTournamentIdMatchupsRouteImport } from './routes/tournaments/$tournamentId/matchups'
import { Route as TournamentsTournamentIdDetailsRouteImport } from './routes/tournaments/$tournamentId/details'
import { Route as TournamentsTournamentIdDecksRouteImport } from './routes/tournaments/$tournamentId/decks'
import { Route as TournamentsTournamentIdCardStatsRouteImport } from './routes/tournaments/$tournamentId/card-stats'
import { Route as DecksDeckIdEditRouteImport } from './routes/decks/$deckId/edit'
import { Route as CardsDetailCardIdRouteImport } from './routes/cards/detail/$cardId'
import { Route as TeamsTeamIdStatisticsIndexRouteImport } from './routes/teams/$teamId/statistics/index'
import { Route as StatisticsStatisticsLayoutMatchupsIndexRouteImport } from './routes/statistics/_statisticsLayout/matchups/index'
import { Route as StatisticsStatisticsLayoutLeaderAndBaseIndexRouteImport } from './routes/statistics/_statisticsLayout/leader-and-base/index'
import { Route as StatisticsStatisticsLayoutHistoryIndexRouteImport } from './routes/statistics/_statisticsLayout/history/index'
import { Route as StatisticsStatisticsLayoutDecksIndexRouteImport } from './routes/statistics/_statisticsLayout/decks/index'
import { Route as StatisticsStatisticsLayoutDashboardIndexRouteImport } from './routes/statistics/_statisticsLayout/dashboard/index'
import { Route as LimitedDeckDeckIdIndexRouteImport } from './routes/limited/deck/$deckId/index'
import { Route as TeamsTeamIdStatisticsStatisticsLayoutRouteImport } from './routes/teams/$teamId/statistics/_statisticsLayout'
import { Route as LimitedPoolPoolIdDetailIndexRouteImport } from './routes/limited/pool/$poolId/detail/index'
import { Route as AuthenticatedSettingsLinkKarabastIndexRouteImport } from './routes/_authenticated/settings/link/karabast/index'
import { Route as TeamsTeamIdStatisticsStatisticsLayoutMembersIndexRouteImport } from './routes/teams/$teamId/statistics/_statisticsLayout/members/index'
import { Route as TeamsTeamIdStatisticsStatisticsLayoutMatchupsIndexRouteImport } from './routes/teams/$teamId/statistics/_statisticsLayout/matchups/index'
import { Route as TeamsTeamIdStatisticsStatisticsLayoutLeaderAndBaseIndexRouteImport } from './routes/teams/$teamId/statistics/_statisticsLayout/leader-and-base/index'
import { Route as TeamsTeamIdStatisticsStatisticsLayoutHistoryIndexRouteImport } from './routes/teams/$teamId/statistics/_statisticsLayout/history/index'
import { Route as TeamsTeamIdStatisticsStatisticsLayoutDecksIndexRouteImport } from './routes/teams/$teamId/statistics/_statisticsLayout/decks/index'
import { Route as TeamsTeamIdStatisticsStatisticsLayoutDashboardIndexRouteImport } from './routes/teams/$teamId/statistics/_statisticsLayout/dashboard/index'

const StatisticsRouteImport = createFileRoute('/statistics')()
const TeamsTeamIdStatisticsRouteImport = createFileRoute(
  '/teams/$teamId/statistics',
)()

const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Statistics2Route = Statistics2RouteImport.update({
  id: '/statistics2',
  path: '/statistics2',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsIndexRoute = StatisticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StatisticsRoute,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaIndexRoute = MetaIndexRouteImport.update({
  id: '/meta/',
  path: '/meta/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const LimitedIndexRoute = LimitedIndexRouteImport.update({
  id: '/limited/',
  path: '/limited/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparerIndexRoute = ComparerIndexRouteImport.update({
  id: '/comparer/',
  path: '/comparer/',
  getParentRoute: () => rootRouteImport,
} as any)
const WantlistsYourRoute = WantlistsYourRouteImport.update({
  id: '/wantlists/your',
  path: '/wantlists/your',
  getParentRoute: () => rootRouteImport,
} as any)
const WantlistsPublicRoute = WantlistsPublicRouteImport.update({
  id: '/wantlists/public',
  path: '/wantlists/public',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsStatisticsLayoutRoute =
  StatisticsStatisticsLayoutRouteImport.update({
    id: '/_statisticsLayout',
    getParentRoute: () => StatisticsRoute,
  } as any)
const ListsYourRoute = ListsYourRouteImport.update({
  id: '/lists/your',
  path: '/lists/your',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksYourRoute = DecksYourRouteImport.update({
  id: '/decks/your',
  path: '/decks/your',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksTournamentRoute = DecksTournamentRouteImport.update({
  id: '/decks/tournament',
  path: '/decks/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksPublicRoute = DecksPublicRouteImport.update({
  id: '/decks/public',
  path: '/decks/public',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksFavoriteRoute = DecksFavoriteRouteImport.update({
  id: '/decks/favorite',
  path: '/decks/favorite',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsYourRoute = CollectionsYourRouteImport.update({
  id: '/collections/your',
  path: '/collections/your',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsPublicRoute = CollectionsPublicRouteImport.update({
  id: '/collections/public',
  path: '/collections/public',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsSearchRoute = CardsSearchRouteImport.update({
  id: '/cards/search',
  path: '/cards/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const TeamsTeamIdStatisticsRoute = TeamsTeamIdStatisticsRouteImport.update({
  id: '/teams/$teamId/statistics',
  path: '/teams/$teamId/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const WantlistsWantlistIdIndexRoute =
  WantlistsWantlistIdIndexRouteImport.update({
    id: '/wantlists/$wantlistId/',
    path: '/wantlists/$wantlistId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UsersUserIdIndexRoute = UsersUserIdIndexRouteImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsPlanetaryQualifiersIndexRoute =
  TournamentsPlanetaryQualifiersIndexRouteImport.update({
    id: '/tournaments/planetary-qualifiers/',
    path: '/tournaments/planetary-qualifiers/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsFeaturedIndexRoute =
  TournamentsFeaturedIndexRouteImport.update({
    id: '/tournaments/featured/',
    path: '/tournaments/featured/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsAllIndexRoute = TournamentsAllIndexRouteImport.update({
  id: '/tournaments/all/',
  path: '/tournaments/all/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentIdIndexRoute =
  TournamentsTournamentIdIndexRouteImport.update({
    id: '/tournaments/$tournamentId/',
    path: '/tournaments/$tournamentId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsDeckFormatConverterIndexRoute =
  ToolsDeckFormatConverterIndexRouteImport.update({
    id: '/tools/deck-format-converter/',
    path: '/tools/deck-format-converter/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamsTeamIdIndexRoute = TeamsTeamIdIndexRouteImport.update({
  id: '/teams/$teamId/',
  path: '/teams/$teamId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsCardListIdIndexRoute = ListsCardListIdIndexRouteImport.update({
  id: '/lists/$cardListId/',
  path: '/lists/$cardListId/',
  getParentRoute: () => rootRouteImport,
} as any)
const LimitedPublicIndexRoute = LimitedPublicIndexRouteImport.update({
  id: '/limited/public/',
  path: '/limited/public/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdIndexRoute = DecksDeckIdIndexRouteImport.update({
  id: '/decks/$deckId/',
  path: '/decks/$deckId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdIndexRoute =
  CollectionsCollectionIdIndexRouteImport.update({
    id: '/collections/$collectionId/',
    path: '/collections/$collectionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const TournamentsTournamentIdMetaRoute =
  TournamentsTournamentIdMetaRouteImport.update({
    id: '/tournaments/$tournamentId/meta',
    path: '/tournaments/$tournamentId/meta',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsTournamentIdMatchupsRoute =
  TournamentsTournamentIdMatchupsRouteImport.update({
    id: '/tournaments/$tournamentId/matchups',
    path: '/tournaments/$tournamentId/matchups',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsTournamentIdDetailsRoute =
  TournamentsTournamentIdDetailsRouteImport.update({
    id: '/tournaments/$tournamentId/details',
    path: '/tournaments/$tournamentId/details',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsTournamentIdDecksRoute =
  TournamentsTournamentIdDecksRouteImport.update({
    id: '/tournaments/$tournamentId/decks',
    path: '/tournaments/$tournamentId/decks',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsTournamentIdCardStatsRoute =
  TournamentsTournamentIdCardStatsRouteImport.update({
    id: '/tournaments/$tournamentId/card-stats',
    path: '/tournaments/$tournamentId/card-stats',
    getParentRoute: () => rootRouteImport,
  } as any)
const DecksDeckIdEditRoute = DecksDeckIdEditRouteImport.update({
  id: '/decks/$deckId/edit',
  path: '/decks/$deckId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsDetailCardIdRoute = CardsDetailCardIdRouteImport.update({
  id: '/cards/detail/$cardId',
  path: '/cards/detail/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdStatisticsIndexRoute =
  TeamsTeamIdStatisticsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TeamsTeamIdStatisticsRoute,
  } as any)
const StatisticsStatisticsLayoutMatchupsIndexRoute =
  StatisticsStatisticsLayoutMatchupsIndexRouteImport.update({
    id: '/matchups/',
    path: '/matchups/',
    getParentRoute: () => StatisticsStatisticsLayoutRoute,
  } as any)
const StatisticsStatisticsLayoutLeaderAndBaseIndexRoute =
  StatisticsStatisticsLayoutLeaderAndBaseIndexRouteImport.update({
    id: '/leader-and-base/',
    path: '/leader-and-base/',
    getParentRoute: () => StatisticsStatisticsLayoutRoute,
  } as any)
const StatisticsStatisticsLayoutHistoryIndexRoute =
  StatisticsStatisticsLayoutHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => StatisticsStatisticsLayoutRoute,
  } as any)
const StatisticsStatisticsLayoutDecksIndexRoute =
  StatisticsStatisticsLayoutDecksIndexRouteImport.update({
    id: '/decks/',
    path: '/decks/',
    getParentRoute: () => StatisticsStatisticsLayoutRoute,
  } as any)
const StatisticsStatisticsLayoutDashboardIndexRoute =
  StatisticsStatisticsLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => StatisticsStatisticsLayoutRoute,
  } as any)
const LimitedDeckDeckIdIndexRoute = LimitedDeckDeckIdIndexRouteImport.update({
  id: '/limited/deck/$deckId/',
  path: '/limited/deck/$deckId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdStatisticsStatisticsLayoutRoute =
  TeamsTeamIdStatisticsStatisticsLayoutRouteImport.update({
    id: '/_statisticsLayout',
    getParentRoute: () => TeamsTeamIdStatisticsRoute,
  } as any)
const LimitedPoolPoolIdDetailIndexRoute =
  LimitedPoolPoolIdDetailIndexRouteImport.update({
    id: '/limited/pool/$poolId/detail/',
    path: '/limited/pool/$poolId/detail/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsLinkKarabastIndexRoute =
  AuthenticatedSettingsLinkKarabastIndexRouteImport.update({
    id: '/settings/link/karabast/',
    path: '/settings/link/karabast/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const TeamsTeamIdStatisticsStatisticsLayoutMembersIndexRoute =
  TeamsTeamIdStatisticsStatisticsLayoutMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => TeamsTeamIdStatisticsStatisticsLayoutRoute,
  } as any)
const TeamsTeamIdStatisticsStatisticsLayoutMatchupsIndexRoute =
  TeamsTeamIdStatisticsStatisticsLayoutMatchupsIndexRouteImport.update({
    id: '/matchups/',
    path: '/matchups/',
    getParentRoute: () => TeamsTeamIdStatisticsStatisticsLayoutRoute,
  } as any)
const TeamsTeamIdStatisticsStatisticsLayoutLeaderAndBaseIndexRoute =
  TeamsTeamIdStatisticsStatisticsLayoutLeaderAndBaseIndexRouteImport.update({
    id: '/leader-and-base/',
    path: '/leader-and-base/',
    getParentRoute: () => TeamsTeamIdStatisticsStatisticsLayoutRoute,
  } as any)
const TeamsTeamIdStatisticsStatisticsLayoutHistoryIndexRoute =
  TeamsTeamIdStatisticsStatisticsLayoutHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => TeamsTeamIdStatisticsStatisticsLayoutRoute,
  } as any)
const TeamsTeamIdStatisticsStatisticsLayoutDecksIndexRoute =
  TeamsTeamIdStatisticsStatisticsLayoutDecksIndexRouteImport.update({
    id: '/decks/',
    path: '/decks/',
    getParentRoute: () => TeamsTeamIdStatisticsStatisticsLayoutRoute,
  } as any)
const TeamsTeamIdStatisticsStatisticsLayoutDashboardIndexRoute =
  TeamsTeamIdStatisticsStatisticsLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => TeamsTeamIdStatisticsStatisticsLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/statistics2': typeof Statistics2Route
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cards/search': typeof CardsSearchRoute
  '/collections/public': typeof CollectionsPublicRoute
  '/collections/your': typeof CollectionsYourRoute
  '/decks/favorite': typeof DecksFavoriteRoute
  '/decks/public': typeof DecksPublicRoute
  '/decks/tournament': typeof DecksTournamentRoute
  '/decks/your': typeof DecksYourRoute
  '/lists/your': typeof ListsYourRoute
  '/statistics': typeof StatisticsStatisticsLayoutRouteWithChildren
  '/wantlists/public': typeof WantlistsPublicRoute
  '/wantlists/your': typeof WantlistsYourRoute
  '/comparer': typeof ComparerIndexRoute
  '/limited': typeof LimitedIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/meta': typeof MetaIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/statistics/': typeof StatisticsIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/cards/detail/$cardId': typeof CardsDetailCardIdRoute
  '/decks/$deckId/edit': typeof DecksDeckIdEditRoute
  '/tournaments/$tournamentId/card-stats': typeof TournamentsTournamentIdCardStatsRoute
  '/tournaments/$tournamentId/decks': typeof TournamentsTournamentIdDecksRoute
  '/tournaments/$tournamentId/details': typeof TournamentsTournamentIdDetailsRoute
  '/tournaments/$tournamentId/matchups': typeof TournamentsTournamentIdMatchupsRoute
  '/tournaments/$tournamentId/meta': typeof TournamentsTournamentIdMetaRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdIndexRoute
  '/decks/$deckId': typeof DecksDeckIdIndexRoute
  '/limited/public': typeof LimitedPublicIndexRoute
  '/lists/$cardListId': typeof ListsCardListIdIndexRoute
  '/teams/$teamId': typeof TeamsTeamIdIndexRoute
  '/tools/deck-format-converter': typeof ToolsDeckFormatConverterIndexRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdIndexRoute
  '/tournaments/all': typeof TournamentsAllIndexRoute
  '/tournaments/featured': typeof TournamentsFeaturedIndexRoute
  '/tournaments/planetary-qualifiers': typeof TournamentsPlanetaryQualifiersIndexRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
  '/wantlists/$wantlistId': typeof WantlistsWantlistIdIndexRoute
  '/teams/$teamId/statistics': typeof TeamsTeamIdStatisticsStatisticsLayoutRouteWithChildren
  '/limited/deck/$deckId': typeof LimitedDeckDeckIdIndexRoute
  '/statistics/dashboard': typeof StatisticsStatisticsLayoutDashboardIndexRoute
  '/statistics/decks': typeof StatisticsStatisticsLayoutDecksIndexRoute
  '/statistics/history': typeof StatisticsStatisticsLayoutHistoryIndexRoute
  '/statistics/leader-and-base': typeof StatisticsStatisticsLayoutLeaderAndBaseIndexRoute
  '/statistics/matchups': typeof StatisticsStatisticsLayoutMatchupsIndexRoute
  '/teams/$teamId/statistics/': typeof TeamsTeamIdStatisticsIndexRoute
  '/settings/link/karabast': typeof AuthenticatedSettingsLinkKarabastIndexRoute
  '/limited/pool/$poolId/detail': typeof LimitedPoolPoolIdDetailIndexRoute
  '/teams/$teamId/statistics/dashboard': typeof TeamsTeamIdStatisticsStatisticsLayoutDashboardIndexRoute
  '/teams/$teamId/statistics/decks': typeof TeamsTeamIdStatisticsStatisticsLayoutDecksIndexRoute
  '/teams/$teamId/statistics/history': typeof TeamsTeamIdStatisticsStatisticsLayoutHistoryIndexRoute
  '/teams/$teamId/statistics/leader-and-base': typeof TeamsTeamIdStatisticsStatisticsLayoutLeaderAndBaseIndexRoute
  '/teams/$teamId/statistics/matchups': typeof TeamsTeamIdStatisticsStatisticsLayoutMatchupsIndexRoute
  '/teams/$teamId/statistics/members': typeof TeamsTeamIdStatisticsStatisticsLayoutMembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/statistics2': typeof Statistics2Route
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cards/search': typeof CardsSearchRoute
  '/collections/public': typeof CollectionsPublicRoute
  '/collections/your': typeof CollectionsYourRoute
  '/decks/favorite': typeof DecksFavoriteRoute
  '/decks/public': typeof DecksPublicRoute
  '/decks/tournament': typeof DecksTournamentRoute
  '/decks/your': typeof DecksYourRoute
  '/lists/your': typeof ListsYourRoute
  '/statistics': typeof StatisticsIndexRoute
  '/wantlists/public': typeof WantlistsPublicRoute
  '/wantlists/your': typeof WantlistsYourRoute
  '/comparer': typeof ComparerIndexRoute
  '/limited': typeof LimitedIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/meta': typeof MetaIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/cards/detail/$cardId': typeof CardsDetailCardIdRoute
  '/decks/$deckId/edit': typeof DecksDeckIdEditRoute
  '/tournaments/$tournamentId/card-stats': typeof TournamentsTournamentIdCardStatsRoute
  '/tournaments/$tournamentId/decks': typeof TournamentsTournamentIdDecksRoute
  '/tournaments/$tournamentId/details': typeof TournamentsTournamentIdDetailsRoute
  '/tournaments/$tournamentId/matchups': typeof TournamentsTournamentIdMatchupsRoute
  '/tournaments/$tournamentId/meta': typeof TournamentsTournamentIdMetaRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdIndexRoute
  '/decks/$deckId': typeof DecksDeckIdIndexRoute
  '/limited/public': typeof LimitedPublicIndexRoute
  '/lists/$cardListId': typeof ListsCardListIdIndexRoute
  '/teams/$teamId': typeof TeamsTeamIdIndexRoute
  '/tools/deck-format-converter': typeof ToolsDeckFormatConverterIndexRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdIndexRoute
  '/tournaments/all': typeof TournamentsAllIndexRoute
  '/tournaments/featured': typeof TournamentsFeaturedIndexRoute
  '/tournaments/planetary-qualifiers': typeof TournamentsPlanetaryQualifiersIndexRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
  '/wantlists/$wantlistId': typeof WantlistsWantlistIdIndexRoute
  '/teams/$teamId/statistics': typeof TeamsTeamIdStatisticsIndexRoute
  '/limited/deck/$deckId': typeof LimitedDeckDeckIdIndexRoute
  '/statistics/dashboard': typeof StatisticsStatisticsLayoutDashboardIndexRoute
  '/statistics/decks': typeof StatisticsStatisticsLayoutDecksIndexRoute
  '/statistics/history': typeof StatisticsStatisticsLayoutHistoryIndexRoute
  '/statistics/leader-and-base': typeof StatisticsStatisticsLayoutLeaderAndBaseIndexRoute
  '/statistics/matchups': typeof StatisticsStatisticsLayoutMatchupsIndexRoute
  '/settings/link/karabast': typeof AuthenticatedSettingsLinkKarabastIndexRoute
  '/limited/pool/$poolId/detail': typeof LimitedPoolPoolIdDetailIndexRoute
  '/teams/$teamId/statistics/dashboard': typeof TeamsTeamIdStatisticsStatisticsLayoutDashboardIndexRoute
  '/teams/$teamId/statistics/decks': typeof TeamsTeamIdStatisticsStatisticsLayoutDecksIndexRoute
  '/teams/$teamId/statistics/history': typeof TeamsTeamIdStatisticsStatisticsLayoutHistoryIndexRoute
  '/teams/$teamId/statistics/leader-and-base': typeof TeamsTeamIdStatisticsStatisticsLayoutLeaderAndBaseIndexRoute
  '/teams/$teamId/statistics/matchups': typeof TeamsTeamIdStatisticsStatisticsLayoutMatchupsIndexRoute
  '/teams/$teamId/statistics/members': typeof TeamsTeamIdStatisticsStatisticsLayoutMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/statistics2': typeof Statistics2Route
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/cards/search': typeof CardsSearchRoute
  '/collections/public': typeof CollectionsPublicRoute
  '/collections/your': typeof CollectionsYourRoute
  '/decks/favorite': typeof DecksFavoriteRoute
  '/decks/public': typeof DecksPublicRoute
  '/decks/tournament': typeof DecksTournamentRoute
  '/decks/your': typeof DecksYourRoute
  '/lists/your': typeof ListsYourRoute
  '/statistics': typeof StatisticsRouteWithChildren
  '/statistics/_statisticsLayout': typeof StatisticsStatisticsLayoutRouteWithChildren
  '/wantlists/public': typeof WantlistsPublicRoute
  '/wantlists/your': typeof WantlistsYourRoute
  '/comparer/': typeof ComparerIndexRoute
  '/limited/': typeof LimitedIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/meta/': typeof MetaIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/statistics/': typeof StatisticsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/cards/detail/$cardId': typeof CardsDetailCardIdRoute
  '/decks/$deckId/edit': typeof DecksDeckIdEditRoute
  '/tournaments/$tournamentId/card-stats': typeof TournamentsTournamentIdCardStatsRoute
  '/tournaments/$tournamentId/decks': typeof TournamentsTournamentIdDecksRoute
  '/tournaments/$tournamentId/details': typeof TournamentsTournamentIdDetailsRoute
  '/tournaments/$tournamentId/matchups': typeof TournamentsTournamentIdMatchupsRoute
  '/tournaments/$tournamentId/meta': typeof TournamentsTournamentIdMetaRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/collections/$collectionId/': typeof CollectionsCollectionIdIndexRoute
  '/decks/$deckId/': typeof DecksDeckIdIndexRoute
  '/limited/public/': typeof LimitedPublicIndexRoute
  '/lists/$cardListId/': typeof ListsCardListIdIndexRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
  '/tools/deck-format-converter/': typeof ToolsDeckFormatConverterIndexRoute
  '/tournaments/$tournamentId/': typeof TournamentsTournamentIdIndexRoute
  '/tournaments/all/': typeof TournamentsAllIndexRoute
  '/tournaments/featured/': typeof TournamentsFeaturedIndexRoute
  '/tournaments/planetary-qualifiers/': typeof TournamentsPlanetaryQualifiersIndexRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
  '/wantlists/$wantlistId/': typeof WantlistsWantlistIdIndexRoute
  '/teams/$teamId/statistics': typeof TeamsTeamIdStatisticsRouteWithChildren
  '/teams/$teamId/statistics/_statisticsLayout': typeof TeamsTeamIdStatisticsStatisticsLayoutRouteWithChildren
  '/limited/deck/$deckId/': typeof LimitedDeckDeckIdIndexRoute
  '/statistics/_statisticsLayout/dashboard/': typeof StatisticsStatisticsLayoutDashboardIndexRoute
  '/statistics/_statisticsLayout/decks/': typeof StatisticsStatisticsLayoutDecksIndexRoute
  '/statistics/_statisticsLayout/history/': typeof StatisticsStatisticsLayoutHistoryIndexRoute
  '/statistics/_statisticsLayout/leader-and-base/': typeof StatisticsStatisticsLayoutLeaderAndBaseIndexRoute
  '/statistics/_statisticsLayout/matchups/': typeof StatisticsStatisticsLayoutMatchupsIndexRoute
  '/teams/$teamId/statistics/': typeof TeamsTeamIdStatisticsIndexRoute
  '/_authenticated/settings/link/karabast/': typeof AuthenticatedSettingsLinkKarabastIndexRoute
  '/limited/pool/$poolId/detail/': typeof LimitedPoolPoolIdDetailIndexRoute
  '/teams/$teamId/statistics/_statisticsLayout/dashboard/': typeof TeamsTeamIdStatisticsStatisticsLayoutDashboardIndexRoute
  '/teams/$teamId/statistics/_statisticsLayout/decks/': typeof TeamsTeamIdStatisticsStatisticsLayoutDecksIndexRoute
  '/teams/$teamId/statistics/_statisticsLayout/history/': typeof TeamsTeamIdStatisticsStatisticsLayoutHistoryIndexRoute
  '/teams/$teamId/statistics/_statisticsLayout/leader-and-base/': typeof TeamsTeamIdStatisticsStatisticsLayoutLeaderAndBaseIndexRoute
  '/teams/$teamId/statistics/_statisticsLayout/matchups/': typeof TeamsTeamIdStatisticsStatisticsLayoutMatchupsIndexRoute
  '/teams/$teamId/statistics/_statisticsLayout/members/': typeof TeamsTeamIdStatisticsStatisticsLayoutMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy'
    | '/statistics2'
    | '/terms'
    | '/admin'
    | '/cards/search'
    | '/collections/public'
    | '/collections/your'
    | '/decks/favorite'
    | '/decks/public'
    | '/decks/tournament'
    | '/decks/your'
    | '/lists/your'
    | '/statistics'
    | '/wantlists/public'
    | '/wantlists/your'
    | '/comparer'
    | '/limited'
    | '/messages'
    | '/meta'
    | '/notifications'
    | '/statistics/'
    | '/teams'
    | '/tools'
    | '/tournaments'
    | '/cards/detail/$cardId'
    | '/decks/$deckId/edit'
    | '/tournaments/$tournamentId/card-stats'
    | '/tournaments/$tournamentId/decks'
    | '/tournaments/$tournamentId/details'
    | '/tournaments/$tournamentId/matchups'
    | '/tournaments/$tournamentId/meta'
    | '/settings'
    | '/collections/$collectionId'
    | '/decks/$deckId'
    | '/limited/public'
    | '/lists/$cardListId'
    | '/teams/$teamId'
    | '/tools/deck-format-converter'
    | '/tournaments/$tournamentId'
    | '/tournaments/all'
    | '/tournaments/featured'
    | '/tournaments/planetary-qualifiers'
    | '/users/$userId'
    | '/wantlists/$wantlistId'
    | '/teams/$teamId/statistics'
    | '/limited/deck/$deckId'
    | '/statistics/dashboard'
    | '/statistics/decks'
    | '/statistics/history'
    | '/statistics/leader-and-base'
    | '/statistics/matchups'
    | '/teams/$teamId/statistics/'
    | '/settings/link/karabast'
    | '/limited/pool/$poolId/detail'
    | '/teams/$teamId/statistics/dashboard'
    | '/teams/$teamId/statistics/decks'
    | '/teams/$teamId/statistics/history'
    | '/teams/$teamId/statistics/leader-and-base'
    | '/teams/$teamId/statistics/matchups'
    | '/teams/$teamId/statistics/members'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy'
    | '/statistics2'
    | '/terms'
    | '/admin'
    | '/cards/search'
    | '/collections/public'
    | '/collections/your'
    | '/decks/favorite'
    | '/decks/public'
    | '/decks/tournament'
    | '/decks/your'
    | '/lists/your'
    | '/statistics'
    | '/wantlists/public'
    | '/wantlists/your'
    | '/comparer'
    | '/limited'
    | '/messages'
    | '/meta'
    | '/notifications'
    | '/teams'
    | '/tools'
    | '/tournaments'
    | '/cards/detail/$cardId'
    | '/decks/$deckId/edit'
    | '/tournaments/$tournamentId/card-stats'
    | '/tournaments/$tournamentId/decks'
    | '/tournaments/$tournamentId/details'
    | '/tournaments/$tournamentId/matchups'
    | '/tournaments/$tournamentId/meta'
    | '/settings'
    | '/collections/$collectionId'
    | '/decks/$deckId'
    | '/limited/public'
    | '/lists/$cardListId'
    | '/teams/$teamId'
    | '/tools/deck-format-converter'
    | '/tournaments/$tournamentId'
    | '/tournaments/all'
    | '/tournaments/featured'
    | '/tournaments/planetary-qualifiers'
    | '/users/$userId'
    | '/wantlists/$wantlistId'
    | '/teams/$teamId/statistics'
    | '/limited/deck/$deckId'
    | '/statistics/dashboard'
    | '/statistics/decks'
    | '/statistics/history'
    | '/statistics/leader-and-base'
    | '/statistics/matchups'
    | '/settings/link/karabast'
    | '/limited/pool/$poolId/detail'
    | '/teams/$teamId/statistics/dashboard'
    | '/teams/$teamId/statistics/decks'
    | '/teams/$teamId/statistics/history'
    | '/teams/$teamId/statistics/leader-and-base'
    | '/teams/$teamId/statistics/matchups'
    | '/teams/$teamId/statistics/members'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/privacy'
    | '/statistics2'
    | '/terms'
    | '/_authenticated/admin'
    | '/cards/search'
    | '/collections/public'
    | '/collections/your'
    | '/decks/favorite'
    | '/decks/public'
    | '/decks/tournament'
    | '/decks/your'
    | '/lists/your'
    | '/statistics'
    | '/statistics/_statisticsLayout'
    | '/wantlists/public'
    | '/wantlists/your'
    | '/comparer/'
    | '/limited/'
    | '/messages/'
    | '/meta/'
    | '/notifications/'
    | '/statistics/'
    | '/teams/'
    | '/tools/'
    | '/tournaments/'
    | '/cards/detail/$cardId'
    | '/decks/$deckId/edit'
    | '/tournaments/$tournamentId/card-stats'
    | '/tournaments/$tournamentId/decks'
    | '/tournaments/$tournamentId/details'
    | '/tournaments/$tournamentId/matchups'
    | '/tournaments/$tournamentId/meta'
    | '/_authenticated/settings/'
    | '/collections/$collectionId/'
    | '/decks/$deckId/'
    | '/limited/public/'
    | '/lists/$cardListId/'
    | '/teams/$teamId/'
    | '/tools/deck-format-converter/'
    | '/tournaments/$tournamentId/'
    | '/tournaments/all/'
    | '/tournaments/featured/'
    | '/tournaments/planetary-qualifiers/'
    | '/users/$userId/'
    | '/wantlists/$wantlistId/'
    | '/teams/$teamId/statistics'
    | '/teams/$teamId/statistics/_statisticsLayout'
    | '/limited/deck/$deckId/'
    | '/statistics/_statisticsLayout/dashboard/'
    | '/statistics/_statisticsLayout/decks/'
    | '/statistics/_statisticsLayout/history/'
    | '/statistics/_statisticsLayout/leader-and-base/'
    | '/statistics/_statisticsLayout/matchups/'
    | '/teams/$teamId/statistics/'
    | '/_authenticated/settings/link/karabast/'
    | '/limited/pool/$poolId/detail/'
    | '/teams/$teamId/statistics/_statisticsLayout/dashboard/'
    | '/teams/$teamId/statistics/_statisticsLayout/decks/'
    | '/teams/$teamId/statistics/_statisticsLayout/history/'
    | '/teams/$teamId/statistics/_statisticsLayout/leader-and-base/'
    | '/teams/$teamId/statistics/_statisticsLayout/matchups/'
    | '/teams/$teamId/statistics/_statisticsLayout/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  PrivacyRoute: typeof PrivacyRoute
  Statistics2Route: typeof Statistics2Route
  TermsRoute: typeof TermsRoute
  CardsSearchRoute: typeof CardsSearchRoute
  CollectionsPublicRoute: typeof CollectionsPublicRoute
  CollectionsYourRoute: typeof CollectionsYourRoute
  DecksFavoriteRoute: typeof DecksFavoriteRoute
  DecksPublicRoute: typeof DecksPublicRoute
  DecksTournamentRoute: typeof DecksTournamentRoute
  DecksYourRoute: typeof DecksYourRoute
  ListsYourRoute: typeof ListsYourRoute
  StatisticsRoute: typeof StatisticsRouteWithChildren
  WantlistsPublicRoute: typeof WantlistsPublicRoute
  WantlistsYourRoute: typeof WantlistsYourRoute
  ComparerIndexRoute: typeof ComparerIndexRoute
  LimitedIndexRoute: typeof LimitedIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  MetaIndexRoute: typeof MetaIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  CardsDetailCardIdRoute: typeof CardsDetailCardIdRoute
  DecksDeckIdEditRoute: typeof DecksDeckIdEditRoute
  TournamentsTournamentIdCardStatsRoute: typeof TournamentsTournamentIdCardStatsRoute
  TournamentsTournamentIdDecksRoute: typeof TournamentsTournamentIdDecksRoute
  TournamentsTournamentIdDetailsRoute: typeof TournamentsTournamentIdDetailsRoute
  TournamentsTournamentIdMatchupsRoute: typeof TournamentsTournamentIdMatchupsRoute
  TournamentsTournamentIdMetaRoute: typeof TournamentsTournamentIdMetaRoute
  CollectionsCollectionIdIndexRoute: typeof CollectionsCollectionIdIndexRoute
  DecksDeckIdIndexRoute: typeof DecksDeckIdIndexRoute
  LimitedPublicIndexRoute: typeof LimitedPublicIndexRoute
  ListsCardListIdIndexRoute: typeof ListsCardListIdIndexRoute
  TeamsTeamIdIndexRoute: typeof TeamsTeamIdIndexRoute
  ToolsDeckFormatConverterIndexRoute: typeof ToolsDeckFormatConverterIndexRoute
  TournamentsTournamentIdIndexRoute: typeof TournamentsTournamentIdIndexRoute
  TournamentsAllIndexRoute: typeof TournamentsAllIndexRoute
  TournamentsFeaturedIndexRoute: typeof TournamentsFeaturedIndexRoute
  TournamentsPlanetaryQualifiersIndexRoute: typeof TournamentsPlanetaryQualifiersIndexRoute
  UsersUserIdIndexRoute: typeof UsersUserIdIndexRoute
  WantlistsWantlistIdIndexRoute: typeof WantlistsWantlistIdIndexRoute
  TeamsTeamIdStatisticsRoute: typeof TeamsTeamIdStatisticsRouteWithChildren
  LimitedDeckDeckIdIndexRoute: typeof LimitedDeckDeckIdIndexRoute
  LimitedPoolPoolIdDetailIndexRoute: typeof LimitedPoolPoolIdDetailIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics2': {
      id: '/statistics2'
      path: '/statistics2'
      fullPath: '/statistics2'
      preLoaderRoute: typeof Statistics2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics/': {
      id: '/statistics/'
      path: '/'
      fullPath: '/statistics/'
      preLoaderRoute: typeof StatisticsIndexRouteImport
      parentRoute: typeof StatisticsRoute
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta/': {
      id: '/meta/'
      path: '/meta'
      fullPath: '/meta'
      preLoaderRoute: typeof MetaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limited/': {
      id: '/limited/'
      path: '/limited'
      fullPath: '/limited'
      preLoaderRoute: typeof LimitedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparer/': {
      id: '/comparer/'
      path: '/comparer'
      fullPath: '/comparer'
      preLoaderRoute: typeof ComparerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wantlists/your': {
      id: '/wantlists/your'
      path: '/wantlists/your'
      fullPath: '/wantlists/your'
      preLoaderRoute: typeof WantlistsYourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wantlists/public': {
      id: '/wantlists/public'
      path: '/wantlists/public'
      fullPath: '/wantlists/public'
      preLoaderRoute: typeof WantlistsPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics/_statisticsLayout': {
      id: '/statistics/_statisticsLayout'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsStatisticsLayoutRouteImport
      parentRoute: typeof StatisticsRoute
    }
    '/lists/your': {
      id: '/lists/your'
      path: '/lists/your'
      fullPath: '/lists/your'
      preLoaderRoute: typeof ListsYourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/your': {
      id: '/decks/your'
      path: '/decks/your'
      fullPath: '/decks/your'
      preLoaderRoute: typeof DecksYourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/tournament': {
      id: '/decks/tournament'
      path: '/decks/tournament'
      fullPath: '/decks/tournament'
      preLoaderRoute: typeof DecksTournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/public': {
      id: '/decks/public'
      path: '/decks/public'
      fullPath: '/decks/public'
      preLoaderRoute: typeof DecksPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/favorite': {
      id: '/decks/favorite'
      path: '/decks/favorite'
      fullPath: '/decks/favorite'
      preLoaderRoute: typeof DecksFavoriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/your': {
      id: '/collections/your'
      path: '/collections/your'
      fullPath: '/collections/your'
      preLoaderRoute: typeof CollectionsYourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/public': {
      id: '/collections/public'
      path: '/collections/public'
      fullPath: '/collections/public'
      preLoaderRoute: typeof CollectionsPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/search': {
      id: '/cards/search'
      path: '/cards/search'
      fullPath: '/cards/search'
      preLoaderRoute: typeof CardsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/teams/$teamId/statistics': {
      id: '/teams/$teamId/statistics'
      path: '/teams/$teamId/statistics'
      fullPath: '/teams/$teamId/statistics'
      preLoaderRoute: typeof TeamsTeamIdStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wantlists/$wantlistId/': {
      id: '/wantlists/$wantlistId/'
      path: '/wantlists/$wantlistId'
      fullPath: '/wantlists/$wantlistId'
      preLoaderRoute: typeof WantlistsWantlistIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/': {
      id: '/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/planetary-qualifiers/': {
      id: '/tournaments/planetary-qualifiers/'
      path: '/tournaments/planetary-qualifiers'
      fullPath: '/tournaments/planetary-qualifiers'
      preLoaderRoute: typeof TournamentsPlanetaryQualifiersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/featured/': {
      id: '/tournaments/featured/'
      path: '/tournaments/featured'
      fullPath: '/tournaments/featured'
      preLoaderRoute: typeof TournamentsFeaturedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/all/': {
      id: '/tournaments/all/'
      path: '/tournaments/all'
      fullPath: '/tournaments/all'
      preLoaderRoute: typeof TournamentsAllIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/': {
      id: '/tournaments/$tournamentId/'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof TournamentsTournamentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/deck-format-converter/': {
      id: '/tools/deck-format-converter/'
      path: '/tools/deck-format-converter'
      fullPath: '/tools/deck-format-converter'
      preLoaderRoute: typeof ToolsDeckFormatConverterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/': {
      id: '/teams/$teamId/'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$cardListId/': {
      id: '/lists/$cardListId/'
      path: '/lists/$cardListId'
      fullPath: '/lists/$cardListId'
      preLoaderRoute: typeof ListsCardListIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limited/public/': {
      id: '/limited/public/'
      path: '/limited/public'
      fullPath: '/limited/public'
      preLoaderRoute: typeof LimitedPublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/': {
      id: '/decks/$deckId/'
      path: '/decks/$deckId'
      fullPath: '/decks/$deckId'
      preLoaderRoute: typeof DecksDeckIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId/': {
      id: '/collections/$collectionId/'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/tournaments/$tournamentId/meta': {
      id: '/tournaments/$tournamentId/meta'
      path: '/tournaments/$tournamentId/meta'
      fullPath: '/tournaments/$tournamentId/meta'
      preLoaderRoute: typeof TournamentsTournamentIdMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/matchups': {
      id: '/tournaments/$tournamentId/matchups'
      path: '/tournaments/$tournamentId/matchups'
      fullPath: '/tournaments/$tournamentId/matchups'
      preLoaderRoute: typeof TournamentsTournamentIdMatchupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/details': {
      id: '/tournaments/$tournamentId/details'
      path: '/tournaments/$tournamentId/details'
      fullPath: '/tournaments/$tournamentId/details'
      preLoaderRoute: typeof TournamentsTournamentIdDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/decks': {
      id: '/tournaments/$tournamentId/decks'
      path: '/tournaments/$tournamentId/decks'
      fullPath: '/tournaments/$tournamentId/decks'
      preLoaderRoute: typeof TournamentsTournamentIdDecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/card-stats': {
      id: '/tournaments/$tournamentId/card-stats'
      path: '/tournaments/$tournamentId/card-stats'
      fullPath: '/tournaments/$tournamentId/card-stats'
      preLoaderRoute: typeof TournamentsTournamentIdCardStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/edit': {
      id: '/decks/$deckId/edit'
      path: '/decks/$deckId/edit'
      fullPath: '/decks/$deckId/edit'
      preLoaderRoute: typeof DecksDeckIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/detail/$cardId': {
      id: '/cards/detail/$cardId'
      path: '/cards/detail/$cardId'
      fullPath: '/cards/detail/$cardId'
      preLoaderRoute: typeof CardsDetailCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/statistics/': {
      id: '/teams/$teamId/statistics/'
      path: '/'
      fullPath: '/teams/$teamId/statistics/'
      preLoaderRoute: typeof TeamsTeamIdStatisticsIndexRouteImport
      parentRoute: typeof TeamsTeamIdStatisticsRoute
    }
    '/statistics/_statisticsLayout/matchups/': {
      id: '/statistics/_statisticsLayout/matchups/'
      path: '/matchups'
      fullPath: '/statistics/matchups'
      preLoaderRoute: typeof StatisticsStatisticsLayoutMatchupsIndexRouteImport
      parentRoute: typeof StatisticsStatisticsLayoutRoute
    }
    '/statistics/_statisticsLayout/leader-and-base/': {
      id: '/statistics/_statisticsLayout/leader-and-base/'
      path: '/leader-and-base'
      fullPath: '/statistics/leader-and-base'
      preLoaderRoute: typeof StatisticsStatisticsLayoutLeaderAndBaseIndexRouteImport
      parentRoute: typeof StatisticsStatisticsLayoutRoute
    }
    '/statistics/_statisticsLayout/history/': {
      id: '/statistics/_statisticsLayout/history/'
      path: '/history'
      fullPath: '/statistics/history'
      preLoaderRoute: typeof StatisticsStatisticsLayoutHistoryIndexRouteImport
      parentRoute: typeof StatisticsStatisticsLayoutRoute
    }
    '/statistics/_statisticsLayout/decks/': {
      id: '/statistics/_statisticsLayout/decks/'
      path: '/decks'
      fullPath: '/statistics/decks'
      preLoaderRoute: typeof StatisticsStatisticsLayoutDecksIndexRouteImport
      parentRoute: typeof StatisticsStatisticsLayoutRoute
    }
    '/statistics/_statisticsLayout/dashboard/': {
      id: '/statistics/_statisticsLayout/dashboard/'
      path: '/dashboard'
      fullPath: '/statistics/dashboard'
      preLoaderRoute: typeof StatisticsStatisticsLayoutDashboardIndexRouteImport
      parentRoute: typeof StatisticsStatisticsLayoutRoute
    }
    '/limited/deck/$deckId/': {
      id: '/limited/deck/$deckId/'
      path: '/limited/deck/$deckId'
      fullPath: '/limited/deck/$deckId'
      preLoaderRoute: typeof LimitedDeckDeckIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/statistics/_statisticsLayout': {
      id: '/teams/$teamId/statistics/_statisticsLayout'
      path: '/teams/$teamId/statistics'
      fullPath: '/teams/$teamId/statistics'
      preLoaderRoute: typeof TeamsTeamIdStatisticsStatisticsLayoutRouteImport
      parentRoute: typeof TeamsTeamIdStatisticsRoute
    }
    '/limited/pool/$poolId/detail/': {
      id: '/limited/pool/$poolId/detail/'
      path: '/limited/pool/$poolId/detail'
      fullPath: '/limited/pool/$poolId/detail'
      preLoaderRoute: typeof LimitedPoolPoolIdDetailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/link/karabast/': {
      id: '/_authenticated/settings/link/karabast/'
      path: '/settings/link/karabast'
      fullPath: '/settings/link/karabast'
      preLoaderRoute: typeof AuthenticatedSettingsLinkKarabastIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/teams/$teamId/statistics/_statisticsLayout/members/': {
      id: '/teams/$teamId/statistics/_statisticsLayout/members/'
      path: '/members'
      fullPath: '/teams/$teamId/statistics/members'
      preLoaderRoute: typeof TeamsTeamIdStatisticsStatisticsLayoutMembersIndexRouteImport
      parentRoute: typeof TeamsTeamIdStatisticsStatisticsLayoutRoute
    }
    '/teams/$teamId/statistics/_statisticsLayout/matchups/': {
      id: '/teams/$teamId/statistics/_statisticsLayout/matchups/'
      path: '/matchups'
      fullPath: '/teams/$teamId/statistics/matchups'
      preLoaderRoute: typeof TeamsTeamIdStatisticsStatisticsLayoutMatchupsIndexRouteImport
      parentRoute: typeof TeamsTeamIdStatisticsStatisticsLayoutRoute
    }
    '/teams/$teamId/statistics/_statisticsLayout/leader-and-base/': {
      id: '/teams/$teamId/statistics/_statisticsLayout/leader-and-base/'
      path: '/leader-and-base'
      fullPath: '/teams/$teamId/statistics/leader-and-base'
      preLoaderRoute: typeof TeamsTeamIdStatisticsStatisticsLayoutLeaderAndBaseIndexRouteImport
      parentRoute: typeof TeamsTeamIdStatisticsStatisticsLayoutRoute
    }
    '/teams/$teamId/statistics/_statisticsLayout/history/': {
      id: '/teams/$teamId/statistics/_statisticsLayout/history/'
      path: '/history'
      fullPath: '/teams/$teamId/statistics/history'
      preLoaderRoute: typeof TeamsTeamIdStatisticsStatisticsLayoutHistoryIndexRouteImport
      parentRoute: typeof TeamsTeamIdStatisticsStatisticsLayoutRoute
    }
    '/teams/$teamId/statistics/_statisticsLayout/decks/': {
      id: '/teams/$teamId/statistics/_statisticsLayout/decks/'
      path: '/decks'
      fullPath: '/teams/$teamId/statistics/decks'
      preLoaderRoute: typeof TeamsTeamIdStatisticsStatisticsLayoutDecksIndexRouteImport
      parentRoute: typeof TeamsTeamIdStatisticsStatisticsLayoutRoute
    }
    '/teams/$teamId/statistics/_statisticsLayout/dashboard/': {
      id: '/teams/$teamId/statistics/_statisticsLayout/dashboard/'
      path: '/dashboard'
      fullPath: '/teams/$teamId/statistics/dashboard'
      preLoaderRoute: typeof TeamsTeamIdStatisticsStatisticsLayoutDashboardIndexRouteImport
      parentRoute: typeof TeamsTeamIdStatisticsStatisticsLayoutRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsLinkKarabastIndexRoute: typeof AuthenticatedSettingsLinkKarabastIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSettingsLinkKarabastIndexRoute:
    AuthenticatedSettingsLinkKarabastIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface StatisticsStatisticsLayoutRouteChildren {
  StatisticsStatisticsLayoutDashboardIndexRoute: typeof StatisticsStatisticsLayoutDashboardIndexRoute
  StatisticsStatisticsLayoutDecksIndexRoute: typeof StatisticsStatisticsLayoutDecksIndexRoute
  StatisticsStatisticsLayoutHistoryIndexRoute: typeof StatisticsStatisticsLayoutHistoryIndexRoute
  StatisticsStatisticsLayoutLeaderAndBaseIndexRoute: typeof StatisticsStatisticsLayoutLeaderAndBaseIndexRoute
  StatisticsStatisticsLayoutMatchupsIndexRoute: typeof StatisticsStatisticsLayoutMatchupsIndexRoute
}

const StatisticsStatisticsLayoutRouteChildren: StatisticsStatisticsLayoutRouteChildren =
  {
    StatisticsStatisticsLayoutDashboardIndexRoute:
      StatisticsStatisticsLayoutDashboardIndexRoute,
    StatisticsStatisticsLayoutDecksIndexRoute:
      StatisticsStatisticsLayoutDecksIndexRoute,
    StatisticsStatisticsLayoutHistoryIndexRoute:
      StatisticsStatisticsLayoutHistoryIndexRoute,
    StatisticsStatisticsLayoutLeaderAndBaseIndexRoute:
      StatisticsStatisticsLayoutLeaderAndBaseIndexRoute,
    StatisticsStatisticsLayoutMatchupsIndexRoute:
      StatisticsStatisticsLayoutMatchupsIndexRoute,
  }

const StatisticsStatisticsLayoutRouteWithChildren =
  StatisticsStatisticsLayoutRoute._addFileChildren(
    StatisticsStatisticsLayoutRouteChildren,
  )

interface StatisticsRouteChildren {
  StatisticsStatisticsLayoutRoute: typeof StatisticsStatisticsLayoutRouteWithChildren
  StatisticsIndexRoute: typeof StatisticsIndexRoute
}

const StatisticsRouteChildren: StatisticsRouteChildren = {
  StatisticsStatisticsLayoutRoute: StatisticsStatisticsLayoutRouteWithChildren,
  StatisticsIndexRoute: StatisticsIndexRoute,
}

const StatisticsRouteWithChildren = StatisticsRoute._addFileChildren(
  StatisticsRouteChildren,
)

interface TeamsTeamIdStatisticsStatisticsLayoutRouteChildren {
  TeamsTeamIdStatisticsStatisticsLayoutDashboardIndexRoute: typeof TeamsTeamIdStatisticsStatisticsLayoutDashboardIndexRoute
  TeamsTeamIdStatisticsStatisticsLayoutDecksIndexRoute: typeof TeamsTeamIdStatisticsStatisticsLayoutDecksIndexRoute
  TeamsTeamIdStatisticsStatisticsLayoutHistoryIndexRoute: typeof TeamsTeamIdStatisticsStatisticsLayoutHistoryIndexRoute
  TeamsTeamIdStatisticsStatisticsLayoutLeaderAndBaseIndexRoute: typeof TeamsTeamIdStatisticsStatisticsLayoutLeaderAndBaseIndexRoute
  TeamsTeamIdStatisticsStatisticsLayoutMatchupsIndexRoute: typeof TeamsTeamIdStatisticsStatisticsLayoutMatchupsIndexRoute
  TeamsTeamIdStatisticsStatisticsLayoutMembersIndexRoute: typeof TeamsTeamIdStatisticsStatisticsLayoutMembersIndexRoute
}

const TeamsTeamIdStatisticsStatisticsLayoutRouteChildren: TeamsTeamIdStatisticsStatisticsLayoutRouteChildren =
  {
    TeamsTeamIdStatisticsStatisticsLayoutDashboardIndexRoute:
      TeamsTeamIdStatisticsStatisticsLayoutDashboardIndexRoute,
    TeamsTeamIdStatisticsStatisticsLayoutDecksIndexRoute:
      TeamsTeamIdStatisticsStatisticsLayoutDecksIndexRoute,
    TeamsTeamIdStatisticsStatisticsLayoutHistoryIndexRoute:
      TeamsTeamIdStatisticsStatisticsLayoutHistoryIndexRoute,
    TeamsTeamIdStatisticsStatisticsLayoutLeaderAndBaseIndexRoute:
      TeamsTeamIdStatisticsStatisticsLayoutLeaderAndBaseIndexRoute,
    TeamsTeamIdStatisticsStatisticsLayoutMatchupsIndexRoute:
      TeamsTeamIdStatisticsStatisticsLayoutMatchupsIndexRoute,
    TeamsTeamIdStatisticsStatisticsLayoutMembersIndexRoute:
      TeamsTeamIdStatisticsStatisticsLayoutMembersIndexRoute,
  }

const TeamsTeamIdStatisticsStatisticsLayoutRouteWithChildren =
  TeamsTeamIdStatisticsStatisticsLayoutRoute._addFileChildren(
    TeamsTeamIdStatisticsStatisticsLayoutRouteChildren,
  )

interface TeamsTeamIdStatisticsRouteChildren {
  TeamsTeamIdStatisticsStatisticsLayoutRoute: typeof TeamsTeamIdStatisticsStatisticsLayoutRouteWithChildren
  TeamsTeamIdStatisticsIndexRoute: typeof TeamsTeamIdStatisticsIndexRoute
}

const TeamsTeamIdStatisticsRouteChildren: TeamsTeamIdStatisticsRouteChildren = {
  TeamsTeamIdStatisticsStatisticsLayoutRoute:
    TeamsTeamIdStatisticsStatisticsLayoutRouteWithChildren,
  TeamsTeamIdStatisticsIndexRoute: TeamsTeamIdStatisticsIndexRoute,
}

const TeamsTeamIdStatisticsRouteWithChildren =
  TeamsTeamIdStatisticsRoute._addFileChildren(
    TeamsTeamIdStatisticsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  PrivacyRoute: PrivacyRoute,
  Statistics2Route: Statistics2Route,
  TermsRoute: TermsRoute,
  CardsSearchRoute: CardsSearchRoute,
  CollectionsPublicRoute: CollectionsPublicRoute,
  CollectionsYourRoute: CollectionsYourRoute,
  DecksFavoriteRoute: DecksFavoriteRoute,
  DecksPublicRoute: DecksPublicRoute,
  DecksTournamentRoute: DecksTournamentRoute,
  DecksYourRoute: DecksYourRoute,
  ListsYourRoute: ListsYourRoute,
  StatisticsRoute: StatisticsRouteWithChildren,
  WantlistsPublicRoute: WantlistsPublicRoute,
  WantlistsYourRoute: WantlistsYourRoute,
  ComparerIndexRoute: ComparerIndexRoute,
  LimitedIndexRoute: LimitedIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  MetaIndexRoute: MetaIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  CardsDetailCardIdRoute: CardsDetailCardIdRoute,
  DecksDeckIdEditRoute: DecksDeckIdEditRoute,
  TournamentsTournamentIdCardStatsRoute: TournamentsTournamentIdCardStatsRoute,
  TournamentsTournamentIdDecksRoute: TournamentsTournamentIdDecksRoute,
  TournamentsTournamentIdDetailsRoute: TournamentsTournamentIdDetailsRoute,
  TournamentsTournamentIdMatchupsRoute: TournamentsTournamentIdMatchupsRoute,
  TournamentsTournamentIdMetaRoute: TournamentsTournamentIdMetaRoute,
  CollectionsCollectionIdIndexRoute: CollectionsCollectionIdIndexRoute,
  DecksDeckIdIndexRoute: DecksDeckIdIndexRoute,
  LimitedPublicIndexRoute: LimitedPublicIndexRoute,
  ListsCardListIdIndexRoute: ListsCardListIdIndexRoute,
  TeamsTeamIdIndexRoute: TeamsTeamIdIndexRoute,
  ToolsDeckFormatConverterIndexRoute: ToolsDeckFormatConverterIndexRoute,
  TournamentsTournamentIdIndexRoute: TournamentsTournamentIdIndexRoute,
  TournamentsAllIndexRoute: TournamentsAllIndexRoute,
  TournamentsFeaturedIndexRoute: TournamentsFeaturedIndexRoute,
  TournamentsPlanetaryQualifiersIndexRoute:
    TournamentsPlanetaryQualifiersIndexRoute,
  UsersUserIdIndexRoute: UsersUserIdIndexRoute,
  WantlistsWantlistIdIndexRoute: WantlistsWantlistIdIndexRoute,
  TeamsTeamIdStatisticsRoute: TeamsTeamIdStatisticsRouteWithChildren,
  LimitedDeckDeckIdIndexRoute: LimitedDeckDeckIdIndexRoute,
  LimitedPoolPoolIdDetailIndexRoute: LimitedPoolPoolIdDetailIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
