#!/usr/bin/env bash

# Opt-in Docker integration test for concurrent SWUBASE worktrees.
#
# It creates two detached Git worktrees, restores both from an empty temporary
# PostgreSQL custom dump, proves database and Docker-resource isolation, then
# purges one worktree while asserting that the other stays healthy.

set -Eeuo pipefail

readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
readonly REPOSITORY_DIR="$(cd -- "${SCRIPT_DIR}/../.." && pwd -P)"
readonly WORKTREE_COMMAND_RELATIVE_PATH="scripts/worktree-dev/swubase-worktree-dev"
readonly POSTGRES_IMAGE="${SWUBASE_WORKTREE_POSTGRES_IMAGE:-postgres:16-alpine}"
readonly TEST_LABEL="com.swubase.test=worktree-integration"

test_root=""
state_root=""
fixture_dump=""
fixture_container=""
first_worktree=""
second_worktree=""

log_info() {
  printf '%s\n' "==> $*"
}

fail() {
  printf '%s\n' "Error: $*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "'$1' is required for this integration test."
}

assert_equal() {
  local expected=$1
  local actual=$2
  local description=$3

  [[ "${expected}" == "${actual}" ]] || fail "${description}: expected '${expected}', got '${actual}'."
}

assert_not_equal() {
  local left=$1
  local right=$2
  local description=$3

  [[ "${left}" != "${right}" ]] || fail "${description} must differ, but both were '${left}'."
}

assert_file_contains() {
  local file=$1
  local expected_text=$2
  local description=$3

  rg -F -q -- "${expected_text}" "${file}" \
    || fail "${description}: '${expected_text}' was not found in ${file}."
}

assert_file_not_contains() {
  local file=$1
  local unexpected_text=$2
  local description=$3

  ! rg -F -q -- "${unexpected_text}" "${file}" \
    || fail "${description}: '${unexpected_text}' was unexpectedly found in ${file}."
}

assert_container_label() {
  local container_name=$1
  local label_name=$2
  local expected_value=$3
  local actual_value

  actual_value=$(docker container inspect --format "{{ index .Config.Labels \"${label_name}\" }}" "${container_name}")
  assert_equal "${expected_value}" "${actual_value}" "Container '${container_name}' label '${label_name}'"
}

assert_volume_label() {
  local volume_name=$1
  local label_name=$2
  local expected_value=$3
  local actual_value

  actual_value=$(docker volume inspect --format "{{ index .Labels \"${label_name}\" }}" "${volume_name}")
  assert_equal "${expected_value}" "${actual_value}" "Volume '${volume_name}' label '${label_name}'"
}

state_value() {
  local worktree_path=$1
  local key=$2

  (
    # State is generated by the CLI and written with bash %q escaping.
    # shellcheck disable=SC1090
    source "${worktree_path}/.swubase/worktree-dev.env"
    case "${key}" in
      id) printf '%s\n' "${SWUBASE_WORKTREE_ID}" ;;
      container) printf '%s\n' "${SWUBASE_DB_CONTAINER}" ;;
      volume) printf '%s\n' "${SWUBASE_DB_VOLUME}" ;;
      database) printf '%s\n' "${SWUBASE_DB_NAME}" ;;
      database-port) printf '%s\n' "${SWUBASE_DB_PORT}" ;;
      backend-port) printf '%s\n' "${SWUBASE_BACKEND_PORT}" ;;
      frontend-port) printf '%s\n' "${SWUBASE_FRONTEND_PORT}" ;;
      public-origin) printf '%s\n' "${SWUBASE_WORKTREE_PUBLIC_ORIGIN}" ;;
      tailscale-serve) printf '%s\n' "${SWUBASE_WORKTREE_TAILSCALE_SERVE}" ;;
      auth-prefix) printf '%s\n' "swubase-${SWUBASE_WORKTREE_ID}" ;;
      *) exit 2 ;;
    esac
  )
}

run_worktree_command() {
  local worktree_path=$1
  shift

  run_worktree_command_with_access \
    "${worktree_path}" \
    'http://localhost:{frontend_port}' \
    false \
    "$@"
}

run_worktree_command_with_access() {
  local worktree_path=$1
  local origin_template=$2
  local tailscale_serve=$3
  shift 3

  (
    cd -- "${worktree_path}"
    SWUBASE_WORKTREE_STATE_ROOT="${state_root}" \
      SWUBASE_WORKTREE_PUBLIC_ORIGIN_TEMPLATE="${origin_template}" \
      SWUBASE_WORKTREE_ACCESS_TAILSCALE_SERVE="${tailscale_serve}" \
      "${worktree_path}/${WORKTREE_COMMAND_RELATIVE_PATH}" "$@"
  )
}

generated_env_value() {
  local worktree_path=$1
  local key=$2

  (
    # Generated by the launcher with bash %q escaping and mode 600.
    # shellcheck disable=SC1090
    source "${worktree_path}/.env.worktree"
    printf '%s\n' "${!key}"
  )
}

cleanup_worktree() {
  local worktree_path=$1

  [[ -n "${worktree_path}" && -d "${worktree_path}" ]] || return 0

  if [[ -f "${worktree_path}/.swubase/worktree-dev.env" ]]; then
    SWUBASE_WORKTREE_STATE_ROOT="${state_root}" \
      "${worktree_path}/${WORKTREE_COMMAND_RELATIVE_PATH}" down --purge-data >/dev/null 2>&1 || true
  fi

  git -C "${REPOSITORY_DIR}" worktree remove --force "${worktree_path}" >/dev/null 2>&1 || true
}

cleanup() {
  local exit_code=$?

  cleanup_worktree "${first_worktree}"
  cleanup_worktree "${second_worktree}"

  if [[ -n "${fixture_container}" ]] && docker container inspect "${fixture_container}" >/dev/null 2>&1; then
    docker rm -f "${fixture_container}" >/dev/null 2>&1 || true
  fi

  if [[ -n "${test_root}" && -d "${test_root}" && "$(basename -- "${test_root}")" == swubase-worktree-integration.* ]]; then
    rm -rf -- "${test_root}"
  fi

  exit "${exit_code}"
}

wait_for_fixture_database() {
  local attempt

  for attempt in {1..30}; do
    if docker exec "${fixture_container}" pg_isready -U postgres -d postgres >/dev/null 2>&1; then
      return 0
    fi
    sleep 1
  done

  docker logs "${fixture_container}" >&2 || true
  fail "Temporary fixture PostgreSQL did not become ready."
}

prepare_fixture_dump() {
  fixture_container="swubase-worktree-integration-fixture-$(date +%s)-${RANDOM}"
  fixture_dump="${test_root}/fixture.dmp"

  log_info "Creating an empty PostgreSQL custom-format fixture dump."
  docker run -d --rm \
    --name "${fixture_container}" \
    --label "${TEST_LABEL}" \
    -e POSTGRES_PASSWORD=fixture \
    "${POSTGRES_IMAGE}" >/dev/null
  wait_for_fixture_database
  docker exec "${fixture_container}" pg_dump -U postgres -Fc -d postgres > "${fixture_dump}"
  [[ -s "${fixture_dump}" ]] || fail "Temporary fixture dump is empty."
}

prepare_worktree() {
  local name=$1
  local worktree_path="${test_root}/${name}"

  git -C "${REPOSITORY_DIR}" worktree add --detach "${worktree_path}" HEAD >/dev/null
  # Exercise local, uncommitted worktree-tooling edits too. The disposable
  # worktree is removed during cleanup, so this does not alter a tracked tree.
  cp -a "${REPOSITORY_DIR}/scripts/worktree-dev/." "${worktree_path}/scripts/worktree-dev/"
  ln -s "${REPOSITORY_DIR}/node_modules" "${worktree_path}/node_modules"
  mkdir -p "${worktree_path}/.idea"
  cat > "${worktree_path}/.idea/dataSources.xml" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="DataSourceManagerImpl" format="xml" multifile-model="true">
    <data-source source="LOCAL" name="Unrelated test source" uuid="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa">
      <driver-ref>postgresql</driver-ref>
      <jdbc-driver>org.postgresql.Driver</jdbc-driver>
      <jdbc-url>jdbc:postgresql://127.0.0.1:5999/unrelated</jdbc-url>
    </data-source>
  </component>
</project>
EOF
  printf '%s\n' "${worktree_path}"
}

main() {
  require_command bun
  require_command docker
  require_command flock
  require_command git
  require_command rg
  require_command sha256sum
  require_command ss

  git -C "${REPOSITORY_DIR}" rev-parse --is-inside-work-tree >/dev/null 2>&1 \
    || fail "Run this test from a Git worktree."
  [[ -d "${REPOSITORY_DIR}/node_modules" ]] \
    || fail "Install root dependencies first with 'bun install'."
  docker info >/dev/null 2>&1 || fail "Docker is unavailable to the current user."
  docker image inspect "${POSTGRES_IMAGE}" >/dev/null 2>&1 \
    || fail "Pull '${POSTGRES_IMAGE}' before running this offline integration test."

  test_root=$(mktemp -d "${TMPDIR:-/tmp}/swubase-worktree-integration.XXXXXX")
  state_root="${test_root}/state"
  trap cleanup EXIT

  prepare_fixture_dump
  first_worktree=$(prepare_worktree first)
  second_worktree=$(prepare_worktree second)

  log_info "Setting up two worktrees from the temporary fixture dump."
  run_worktree_command "${first_worktree}" setup --dump "${fixture_dump}"
  run_worktree_command "${second_worktree}" setup --dump "${fixture_dump}"

  local first_id second_id first_container second_container first_volume second_volume
  local first_database second_database first_db_port second_db_port first_backend_port second_backend_port
  local first_frontend_port second_frontend_port first_auth_prefix second_auth_prefix
  local first_public_origin second_public_origin first_tailscale_serve second_tailscale_serve

  first_id=$(state_value "${first_worktree}" id)
  second_id=$(state_value "${second_worktree}" id)
  first_container=$(state_value "${first_worktree}" container)
  second_container=$(state_value "${second_worktree}" container)
  first_volume=$(state_value "${first_worktree}" volume)
  second_volume=$(state_value "${second_worktree}" volume)
  first_database=$(state_value "${first_worktree}" database)
  second_database=$(state_value "${second_worktree}" database)
  first_db_port=$(state_value "${first_worktree}" database-port)
  second_db_port=$(state_value "${second_worktree}" database-port)
  first_backend_port=$(state_value "${first_worktree}" backend-port)
  second_backend_port=$(state_value "${second_worktree}" backend-port)
  first_frontend_port=$(state_value "${first_worktree}" frontend-port)
  second_frontend_port=$(state_value "${second_worktree}" frontend-port)
  first_public_origin=$(state_value "${first_worktree}" public-origin)
  second_public_origin=$(state_value "${second_worktree}" public-origin)
  first_tailscale_serve=$(state_value "${first_worktree}" tailscale-serve)
  second_tailscale_serve=$(state_value "${second_worktree}" tailscale-serve)
  first_auth_prefix=$(state_value "${first_worktree}" auth-prefix)
  second_auth_prefix=$(state_value "${second_worktree}" auth-prefix)

  assert_not_equal "${first_id}" "${second_id}" "Worktree identities"
  assert_not_equal "${first_container}" "${second_container}" "Database containers"
  assert_not_equal "${first_volume}" "${second_volume}" "Database volumes"
  assert_not_equal "${first_database}" "${second_database}" "Database names"
  assert_not_equal "${first_db_port}" "${second_db_port}" "Database ports"
  assert_not_equal "${first_backend_port}" "${second_backend_port}" "Backend ports"
  assert_not_equal "${first_frontend_port}" "${second_frontend_port}" "Frontend ports"
  assert_equal "http://localhost:${first_frontend_port}" "${first_public_origin}" "First public origin"
  assert_equal "http://localhost:${second_frontend_port}" "${second_public_origin}" "Second public origin"
  assert_equal false "${first_tailscale_serve}" "First Tailscale Serve mode"
  assert_equal false "${second_tailscale_serve}" "Second Tailscale Serve mode"
  assert_not_equal "${first_auth_prefix}" "${second_auth_prefix}" "Auth cookie prefixes"

  local first_datasource_file="${first_worktree}/.idea/dataSources.xml"
  local second_datasource_file="${second_worktree}/.idea/dataSources.xml"
  assert_file_contains "${first_datasource_file}" 'name="Unrelated test source"' \
    "First unrelated JetBrains datasource preservation"
  assert_file_contains "${second_datasource_file}" 'name="Unrelated test source"' \
    "Second unrelated JetBrains datasource preservation"
  assert_file_contains "${first_datasource_file}" \
    "jdbc:postgresql://127.0.0.1:${first_db_port}/${first_database}?user=postgres&amp;password=password" \
    "First generated JetBrains datasource URL"
  assert_file_contains "${second_datasource_file}" \
    "jdbc:postgresql://127.0.0.1:${second_db_port}/${second_database}?user=postgres&amp;password=password" \
    "Second generated JetBrains datasource URL"

  log_info "Switching the stopped second worktree to an external HTTPS access profile."
  run_worktree_command_with_access \
    "${second_worktree}" \
    'https://worktree-test.example.test:{frontend_port}' \
    false \
    setup
  second_public_origin=$(state_value "${second_worktree}" public-origin)
  assert_equal "https://worktree-test.example.test:${second_frontend_port}" "${second_public_origin}" \
    "Second external public origin"
  assert_equal "${second_public_origin}" \
    "$(generated_env_value "${second_worktree}" VITE_BETTER_AUTH_URL)" \
    "Generated frontend auth origin"
  assert_equal /api/ws/game-results \
    "$(generated_env_value "${second_worktree}" VITE_GAME_RESULTS_WS_URL)" \
    "Generated game-results WebSocket path"
  assert_equal /api/ws/live-tournaments/:weekendId \
    "$(generated_env_value "${second_worktree}" VITE_LIVE_TOURNAMENT_WS_URL)" \
    "Generated live-tournaments WebSocket path"

  assert_container_label "${first_container}" com.swubase.worktree-id "${first_id}"
  assert_container_label "${second_container}" com.swubase.worktree-id "${second_id}"
  assert_volume_label "${first_volume}" com.swubase.worktree-id "${first_id}"
  assert_volume_label "${second_volume}" com.swubase.worktree-id "${second_id}"

  docker exec "${first_container}" psql -U postgres -d "${first_database}" -v ON_ERROR_STOP=1 -c \
    'CREATE TABLE worktree_integration_sentinel (id integer PRIMARY KEY); INSERT INTO worktree_integration_sentinel VALUES (1);' >/dev/null
  assert_equal t "$(docker exec "${second_container}" psql -U postgres -d "${second_database}" -Atqc "SELECT to_regclass('public.worktree_integration_sentinel') IS NULL;")" \
    "Database data isolation"

  log_info "Purging the first worktree and verifying the second remains ready."
  run_worktree_command "${first_worktree}" down --purge-data
  ! docker container inspect "${first_container}" >/dev/null 2>&1 \
    || fail "First worktree container still exists after purge."
  ! docker volume inspect "${first_volume}" >/dev/null 2>&1 \
    || fail "First worktree volume still exists after purge."
  [[ ! -f "${first_worktree}/.swubase/worktree-dev.env" ]] \
    || fail "First worktree state still exists after purge."
  assert_file_contains "${first_datasource_file}" 'name="Unrelated test source"' \
    "First unrelated JetBrains datasource remains after purge"
  assert_file_not_contains "${first_datasource_file}" \
    "jdbc:postgresql://127.0.0.1:${first_db_port}/${first_database}?user=postgres&amp;password=password" \
    "First generated JetBrains datasource removal"
  assert_file_contains "${second_datasource_file}" \
    "jdbc:postgresql://127.0.0.1:${second_db_port}/${second_database}?user=postgres&amp;password=password" \
    "Second generated JetBrains datasource remains after first purge"
  docker exec "${second_container}" pg_isready -U postgres -d "${second_database}" >/dev/null \
    || fail "Second worktree database was affected by first-worktree cleanup."

  printf '%s\n' 'PASS: concurrent worktree Docker isolation and one-way cleanup verified.'
}

main "$@"
